# Generated by Django 4.1.4 on 2022-12-21 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_centralgovernment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=0)),
                ('timer', models.DurationField(default=0)),
                ('start_time', models.TimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
