# Generated by Django 4.1.4 on 2022-12-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_group_power_group_primary_food_group_primary_fuel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('consumption_water', models.IntegerField(default=0)),
                ('consumption_food', models.IntegerField(default=0)),
                ('consumption_fuel', models.IntegerField(default=0)),
                ('consumption_gold', models.IntegerField(default=0)),
                ('consumption_ap', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='action_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='money',
            field=models.IntegerField(default=0),
        ),
    ]
