# Generated by Django 4.1.4 on 2022-12-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_actions_group_action_point_group_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='title_fa',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
