# Generated by Django 4.1.4 on 2022-12-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_group_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name_fa',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
