# Generated by Django 4.1.4 on 2022-12-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_resource_name_fa'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplocation',
            name='neighbor_Locations',
            field=models.ManyToManyField(to='core.maplocation'),
        ),
    ]
